apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-chart.fullname" . }}
  labels:
    {{- include "python-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # ports:
  #   - port: {{ .Values.service.port }}
  #     targetPort: http
  #     protocol: TCP
  #     name: http
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "python-chart.selectorLabels" . | nindent 4 }}
